import { Course, Provider } from '../types/course';

export const CATEGORIES = [
  'Development',
  'Design',
  'Data Science',
  'Business',
  'Marketing',
  'Personal Development',
];

export const PROVIDERS: { id: Provider; name: string; color: string }[] = [
  { id: 'udemy', name: 'Udemy', color: '#A435F0' },
  { id: 'coursera', name: 'Coursera', color: '#0056D2' },
  { id: 'youtube', name: 'YouTube', color: '#FF0000' },
  { id: 'edx', name: 'edX', color: '#02262B' },
];

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title: 'Modern React with Redux [2024 Update]',
    slug: 'modern-react-redux',
    description: 'Master React and Redux with React Router, Webpack, and Create-React-App. Includes Hooks!',
    shortDescription: 'Master React and Redux with React Router, Webpack, and Create-React-App.',
    provider: 'udemy',
    affiliateUrl: 'https://www.udemy.com/course/react-redux/',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'Stephen Grider',
      avatar: 'https://i.pravatar.cc/150?u=stephen',
    },
    rating: 4.8,
    reviewCount: 12540,
    enrollmentCount: 450000,
    duration: 1240,
    level: 'beginner',
    price: 89.99,
    originalPrice: 129.99,
    language: 'English',
    lastUpdated: '2024-01-15',
    tags: ['React', 'Redux', 'Frontend'],
    category: 'Development',
    subcategory: 'Web Development',
    whatYouLearn: ['Build dynamic web apps', 'Master React Hooks', 'State management with Redux'],
    prerequisites: ['Basic HTML/CSS', 'JavaScript fundamentals'],
  },
  {
    id: '2',
    title: 'Google Data Analytics Professional Certificate',
    slug: 'google-data-analytics',
    description: 'Get on the fast track to a career in data analytics. In this program, you’ll learn in-demand skills.',
    shortDescription: 'Get on the fast track to a career in data analytics.',
    provider: 'coursera',
    affiliateUrl: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'Google Career Certificates',
      avatar: 'https://i.pravatar.cc/150?u=google',
    },
    rating: 4.9,
    reviewCount: 85000,
    enrollmentCount: 1200000,
    duration: 14400,
    level: 'beginner',
    price: 0,
    language: 'English',
    lastUpdated: '2024-02-10',
    tags: ['Data Analytics', 'SQL', 'R'],
    category: 'Data Science',
    subcategory: 'Data Analysis',
    whatYouLearn: ['Data cleaning', 'Data visualization', 'SQL and R programming'],
    prerequisites: ['No prior experience needed'],
  },
  {
    id: '3',
    title: 'Figma UI UX Design Essentials',
    slug: 'figma-design-essentials',
    description: 'Use Figma to get a job in UI Design, User Interface, User Experience design, UX Design & Web Design.',
    shortDescription: 'Use Figma to get a job in UI Design and UX Design.',
    provider: 'udemy',
    affiliateUrl: 'https://www.udemy.com/course/figma-ui-ux-design-essentials/',
    thumbnail: 'https://images.unsplash.com/photo-1586717791821-3f44a563dc4c?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'Daniel Walter Scott',
      avatar: 'https://i.pravatar.cc/150?u=daniel',
    },
    rating: 4.7,
    reviewCount: 22000,
    enrollmentCount: 150000,
    duration: 720,
    level: 'beginner',
    price: 19.99,
    originalPrice: 94.99,
    language: 'English',
    lastUpdated: '2023-11-20',
    tags: ['Figma', 'UI Design', 'UX Design'],
    category: 'Design',
    subcategory: 'UI/UX Design',
    whatYouLearn: ['Master Figma', 'Design mobile apps', 'Create interactive prototypes'],
    prerequisites: ['No design experience needed'],
  },
  {
    id: '4',
    title: 'CS50\'s Introduction to Computer Science',
    slug: 'cs50-intro',
    description: 'An introduction to the intellectual enterprises of computer science and the art of programming.',
    shortDescription: 'An introduction to the intellectual enterprises of computer science.',
    provider: 'edx',
    affiliateUrl: 'https://www.edx.org/course/introduction-computer-science-harvardx-cs50x',
    thumbnail: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'David J. Malan',
      avatar: 'https://i.pravatar.cc/150?u=david',
    },
    rating: 4.9,
    reviewCount: 150000,
    enrollmentCount: 5000000,
    duration: 6600,
    level: 'beginner',
    price: 0,
    language: 'English',
    lastUpdated: '2024-01-01',
    tags: ['Computer Science', 'C', 'Python'],
    category: 'Development',
    subcategory: 'Computer Science',
    whatYouLearn: ['C, Python, SQL', 'Data structures', 'Algorithms'],
    prerequisites: ['None'],
  },
  {
    id: '5',
    title: 'Next.js 14 Full Course 2024',
    slug: 'nextjs-14-full-course',
    description: 'Learn Next.js 14 from scratch with App Router, Server Components, and more.',
    shortDescription: 'Learn Next.js 14 from scratch with App Router.',
    provider: 'youtube',
    affiliateUrl: 'https://www.youtube.com/watch?v=wm5gMKuwSYk',
    thumbnail: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'JavaScript Mastery',
      avatar: 'https://i.pravatar.cc/150?u=jsmastery',
    },
    rating: 4.9,
    reviewCount: 5000,
    enrollmentCount: 250000,
    duration: 360,
    level: 'intermediate',
    price: 0,
    language: 'English',
    lastUpdated: '2024-03-01',
    tags: ['Next.js', 'React', 'Fullstack'],
    category: 'Development',
    subcategory: 'Web Development',
    whatYouLearn: ['App Router', 'Server Components', 'Server Actions'],
    prerequisites: ['React fundamentals'],
  },
  {
    id: '6',
    title: 'Machine Learning A-Z™: AI, Python & R',
    slug: 'machine-learning-az',
    description: 'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts.',
    shortDescription: 'Learn to create Machine Learning Algorithms in Python and R.',
    provider: 'udemy',
    affiliateUrl: 'https://www.udemy.com/course/machinelearning/',
    thumbnail: 'https://images.unsplash.com/photo-1527477321055-49419b0bf0c0?auto=format&fit=crop&q=80&w=800&h=450',
    instructor: {
      name: 'Kirill Eremenko',
      avatar: 'https://i.pravatar.cc/150?u=kirill',
    },
    rating: 4.5,
    reviewCount: 165000,
    enrollmentCount: 950000,
    duration: 2640,
    level: 'intermediate',
    price: 14.99,
    originalPrice: 84.99,
    language: 'English',
    lastUpdated: '2024-02-28',
    tags: ['Machine Learning', 'Python', 'AI'],
    category: 'Data Science',
    subcategory: 'Machine Learning',
    whatYouLearn: ['Regression', 'Classification', 'Clustering'],
    prerequisites: ['High school math'],
  }
];

export const ROADMAPS = [
  {
    id: 'frontend',
    title: 'Frontend Developer',
    slug: 'frontend-developer',
    description: 'Master the art of building beautiful, responsive, and performant user interfaces.',
    duration: '6-8 months',
    courseCount: 12,
    icon: 'Layout',
  },
  {
    id: 'data-science',
    title: 'Data Science',
    slug: 'data-science',
    description: 'Learn to extract insights from data using statistical methods and machine learning.',
    duration: '8-10 months',
    courseCount: 15,
    icon: 'Database',
  },
  {
    id: 'ui-ux',
    title: 'UI/UX Design',
    slug: 'ui-ux-design',
    description: 'Design intuitive and engaging user experiences from research to high-fidelity prototypes.',
    duration: '4-6 months',
    courseCount: 8,
    icon: 'Palette',
  },
  {
    id: 'backend',
    title: 'Backend Developer',
    slug: 'backend-developer',
    description: 'Build scalable APIs, manage databases, and handle server-side logic.',
    duration: '6-8 months',
    courseCount: 10,
    icon: 'Server',
  },
  {
    id: 'devops',
    title: 'DevOps Engineer',
    slug: 'devops-engineer',
    description: 'Bridge the gap between development and operations with automation and cloud infrastructure.',
    duration: '8-12 months',
    courseCount: 14,
    icon: 'Cloud',
  },
  {
    id: 'machine-learning',
    title: 'Machine Learning',
    slug: 'machine-learning',
    description: 'Dive deep into neural networks, deep learning, and artificial intelligence.',
    duration: '10-14 months',
    courseCount: 18,
    icon: 'Cpu',
  },
];
